# Generated by Django 3.0.8 on 2020-07-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ('nombre',), 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Abierto'), (1, 'Completado')], default=0),
        ),
    ]
