# Generated by Django 3.0.8 on 2020-07-23 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0002_auto_20200719_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion1', models.CharField(max_length=100, verbose_name='Dirección 1')),
                ('direccion2', models.CharField(blank=True, max_length=100, verbose_name='Direccion 2')),
                ('ciudad', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('zip_code', models.CharField(max_length=200, verbose_name='Codigo postal')),
                ('pais', models.CharField(choices=[('mx', 'Mexico'), ('eu', 'EUA')], max_length=3)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
