# Generated by Django 3.0.8 on 2020-07-23 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200722_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='direccion',
            options={'verbose_name_plural': 'Direcciones'},
        ),
    ]
